# air.toml

entry = "main.go"

[build]
cmd = "go build -o main ."
bin = "main"
stop_on_error = true
src = "./"
exclude = [
    "assets",
    "docs",
    "test",
    "tmp",
]

[web]
  # HTTP server port.
  addr = ":8080"

[screen]
clear_on_rebuild = true
keep_scroll = true